### ISSUE TITLE
DateUtils not found

### ISSUE THREAD

**Issue by sigfrido** [amat-mi/AMATOSMEditor#10]
Diagnosi: DateUtils spostato in org.openstreetmap.josm.tools.**date**

Su JOSM 7723: attivando AMAT copy Way:

``
Repository Root: http://josm.openstreetmap.de/svn
Build-Date: 2014-11-13 02:34:10
Last Changed Author: Klumbumbus
Revision: 7723
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Relative URL: ^/trunk
URL: http://josm.openstreetmap.de/svn/trunk
Last Changed Date: 2014-11-12 22:45:27 +0100 (Wed, 12 Nov 2014)
Last Changed Rev: 7723

Identification: JOSM/1.5 (7723 it) Linux Ubuntu 14.04.1 LTS
Memory Usage: 707 MB / 1762 MB (116 MB allocated, but free)
Java version: 1.7.0_65, Oracle Corporation, OpenJDK 64-Bit Server VM
Java package: openjdk-7-jre:amd64-7u71-2.5.3-0ubuntu0.14.04.1
VM arguments: [-Djosm.restart=true, -Djosm.home=/home/sigfrido/.josm-latest, -Djava.net.useSystemProxies=true]
Dataset consistency test: No problems found

Plugins:
- AMATOSMEditor (${version.entry.commit.revision})
- CommandLine (30762)
- RoadSigns (30788)
- conflation (0.1.7)
- jts (30762)
- public_transport (30762)
- scripting (30701)
- utilsplugin2 (30762)

Last errors/warnings:
- W: org.openstreetmap.josm.io.OsmTransferException: Impossibile connettersi al server osm. Controllare la propria connessione ad internet.. Causa: java.net.SocketException: Unknown proxy type : HTTP
- E: java.lang.NoClassDefFoundError: org/openstreetmap/josm/tools/DateUtils. Causa: java.lang.ClassNotFoundException: org.openstreetmap.josm.tools.DateUtils
- E: java.lang.NoClassDefFoundError: org/openstreetmap/josm/tools/DateUtils
- E: java.lang.NoClassDefFoundError: org/openstreetmap/josm/tools/DateUtils
- E: java.lang.NoClassDefFoundError: org/openstreetmap/josm/tools/DateUtils

java.lang.NoClassDefFoundError: org/openstreetmap/josm/tools/DateUtils
	at org.openstreetmap.josm.plugins.amatosmeditor.gui.dialogs.AMATComparePrimitiveDialog$DataText.addCommon(AMATComparePrimitiveDialog.java:312)
	at org.openstreetmap.josm.plugins.amatosmeditor.gui.dialogs.AMATComparePrimitiveDialog$DataText.addPrimitive(AMATComparePrimitiveDialog.java:247)
	at org.openstreetmap.josm.plugins.amatosmeditor.gui.dialogs.AMATComparePrimitiveDialog.buildDataTextArea(AMATComparePrimitiveDialog.java:160)
	at org.openstreetmap.josm.plugins.amatosmeditor.gui.dialogs.AMATComparePrimitiveDialog.buildDataPanel(AMATComparePrimitiveDialog.java:147)
	at org.openstreetmap.josm.plugins.amatosmeditor.gui.dialogs.AMATComparePrimitiveDialog.<init>(AMATComparePrimitiveDialog.java:108)
	at org.openstreetmap.josm.plugins.amatosmeditor.CopyWayAction.actionPerformed(CopyWayAction.java:155)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1662)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2869)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:263)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2961)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2953)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6293)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4742)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
``

**Comment by caipirginka** [comment]
Fixed by eaa24a6a0533f2502222d785e4df0471e6e10ef0 (Note that plugin is now compatible with JOSM version >= 7906).
